== Configuration du plugin

Après l'installation du plugin dans Jeedom, il vous faut l'activer. Vous le retrouverez dans le menu *Plugins->Communication->Gcast*.
Il va sans dire qu'une Google Home ou Google Home mini est nécessaire pour la bonne utilisation du plugin.

== Ajout d'une Google Home

Pour bien démarrer, il faut ajouter votre Google Home :

* Cliquez sur *Ajouter*,
* Donnez un *nom* à votre Google Home,
* Renseignez les champs habituels : *Objet parent*, *Catégorie*,
* Renseignez l'adresse *IP* de votre Google Home,
* Choisissez un *moteur TTS* (c'est le système de synthèse vocale qui sera utilisé par votre Google Home),
* Choisissez la *voix* utilisée (la langue parlée par le moteur TTS).

[TIP]
L'adresse IP de votre Google Home doit être fixe. Cela se règle dans les paramètres de votre box Internet. C'est aussi dans les paramètres de celle-ci que vous trouverez son adresse IP.

== Configuration de IFTTT pour le retour TTS

https://ifttt.com[IFTTT] est, pour le moment, un passage obligé pour dialoguer entre votre Google Home et Jeedom. Il faut donc y créer un compte et le configurer pour faire le lien entre les deux.

=== Configuration de IFTTT

* Se connecter et/ou s'inscrire sur https://ifttt.com[IFTTT] (ou via l'application mobile),
* Cliquez sur l'onglet *My Applets*, puis *New Applet*,
* Cliquez sur *+This*,
* Choisissez *Google Assistant* (lier votre Google Assistant à IFTTT si ce n'est pas déjà fait),
* Choisissez le trigger *Say a phrase with a text ingredient*.

Vous pouvez maintenant configurer l'interaction entre Google Assistant et Jeedom par cette nouvelle applet.

=== Exemple de configuration de la première partie de l'Applet

* *What do you want to say?* : `dis à jeedom $`
[TIP]
Il faut absolument mettre *$* à la fin de votre phrase. C'est ce symbole qui fera que le reste de la phrase sera envoyé à Jeedom.
* *What's another way to say it? (optional)* : `maison $`
* *And another way? (optional)* : `jarvis $`
* *What do you want the Assistant to say in response?* : `Je m'exécute`
[TIP]
Ici, il s'agit de la phrase que votre Google Assistant va répondre avant qu'il n'envoie votre demande à Jeedom.
* *Language* : French
* Cliquez sur *+That*, choisissez *Webhooks* (activez le service si ce n'est pas déjà fait),
* Choisissez le seul trigger disponible : *Make a web request*

=== Exemple de configuration de la deuxième partie de l'Applet

* *URL* : Vous devez recopier l'URL de retour indiquée dans la page de votre équipement, dans le plugin Gcast. Elle doit être modifiée :
  ** *#ID_EQUIPEMENT#* doit être remplacé par l'*ID* de votre Google Assistant (Cliquez sur *Configuration avancée* sur la page de votre équipement pour le trouver)
  ** *#query=XXXX#* par `*query=<\<<{{TextField}}\>>>*`
  
[TIP]
La clé API est celle du plugin Gcast. Elle est retrouvable dans *Administration->Configuration->API*. De la même manière, l'URL doit commencer par l'adresse externe de votre Jeedom, en HTTP ou HTTPS, suivant votre configuration. Veillez à bien paramétrer la configuration réseau de votre Jeedom dans *Administration->Configuration->Réseaux*

* *Method* : `GET`
* *Content type* : `application/json`
* *Body* : `<\<<{{TextField}}\>>>`
* Il ne reste plus qu'à sauvegarder en cliquant sur le bouton *Save*.

Il faut maintenant configurer des *interactions* dans Jeedom dans le menu *Outils->Interactions*. La partie *Demande* devra correspondre à ce que vous dites à la place du *$* dans le message énoncé à votre Google Home.

L'utilisation de ASK est même possible.

=== Les commandes d'un équipement

Vous pouvez retrouver ces commandes, notamment, sur le *dashboard*. Elles sont également utilisables dans les *scénarios* ou dans les commandes des *interactions* par exemple.

* *Parle* : Permet d'envoyer un message vocal à votre Google Home. Si aucune phrase n'est renseignée, une phrase de test sera tout de même envoyée.
* *Vol-* : Permet de baisser le volume de votre Google Home.
* *Vol+* : Permet de monter le volume de votre Google Home.
* *Volume* : Permet de modifier le volume de votre Google Home.

[TIP]
La commande ASK de Jeedom peut être utilisée avec ce plugin !

[NOTE]
Pour le moment, le temps pour envoyer l'énoncé de la phrase peut être relativement long. Il se peut qu'il se passe près d'une dizaine de secondes entre l'envoi de la commande et la diction de la phrase par votre Google Home.
